"""KETAMINE: branch into possible worlds under a finite budget.

FORMAL OBJECT.  A rooted tree of *simulated* states generated by interventions.
Each branch carries the assumptions its path introduced.  Given recorded evidence
``E``, a value function on terminals, a node budget ``B`` and optionally a bound
``h`` on the best value reachable from a state, choose which branches to expand.

ACTION SPACE.  A subset of the frontier to expand.  It buys no observation, makes
no trajectory decision, and preserves the representation: what it manipulates is a
set of hypothetical futures.

MODAL DISCIPLINE.  Every generated node has ``status = SIMULATED``; only the root
is ``OBSERVED``; a node whose assumptions contradict ``E`` is ``REJECTED`` and is
never expanded.  No operation in this module can promote a simulated node to
observed, so the three modalities cannot be confused by construction:

    observed != simulated      the status field, enforced at generation
    possible != probable       no probability is attached to a branch at all
    probable != true           nothing here asserts truth of a simulated value

LITERATURE AUDIT.
* Branch and bound -- ESTABLISHED (Land & Doig 1960; Lawler & Wood 1966).  With an
  admissible bound the pruning is safe, which is verified against the exhaustive
  oracle in every world.
* Best-first search and A* optimality under admissibility -- KNOWN_RESULT (Hart,
  Nilsson & Raphael 1968).
* Beam search is incomplete -- KNOWN_RESULT; ``worlds.trap_world`` instantiates the
  standard failure where the optimal prefix has the worst immediate score.
* Counterfactual reasoning requires consistency with the factual record --
  IMPORTED (Pearl, *Causality*, 2009, ch. 7: the abduction-action-prediction
  procedure conditions on the observed evidence before intervening).  The check
  implemented here is the finite, syntactic special case: reject a branch whose
  assumption set contains the negation of a recorded fact.
* Monte Carlo Tree Search -- KNOWN_RESULT (Kocsis & Szepesvari 2006).
  **Deliberately not used.**  These worlds are finite, deterministic and equipped
  with an admissible bound, so branch and bound is exact and cheaper; UCT's
  guarantee is asymptotic and buys nothing here.  Adding it would be decoration.

WHAT REMAINS SPECIFIC TO MAT-SI.  The consistency filter as a first-class stage
before any value comparison, and the explicit report of what pruning discarded so
an unsafe prune is visible rather than silent.

FAILURE REGIME.  Without an admissible bound, breadth limits lose the optimum
(``trap_world``); and diversity-driven expansion spends the whole budget on
mutually dissimilar worthless branches (``novelty_trap_world``).
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Hashable, Sequence

from ..substrate import Candidate, Declaration, Decision, State
from ..worlds.branch_world import Branch, BranchWorld

OBSERVED = "OBSERVED"
SIMULATED = "SIMULATED"
REJECTED = "REJECTED"


@dataclass
class KetamineConfig:
    node_budget: int = 24
    beam_width: int | None = None
    """``None`` uses bound-guided best-first; an integer switches to a layered beam."""

    diversity_first: bool = False
    """Expand by dissimilarity instead of by bound.  Used to exhibit its failure."""


@dataclass
class BranchReport:
    """What a branching run did, in enough detail to audit the pruning."""

    world: str
    strategy: str
    expanded: int = 0
    generated: int = 0
    rejected: list[dict[str, object]] = field(default_factory=list)
    pruned: list[dict[str, object]] = field(default_factory=list)
    best_value: float | None = None
    best_path: tuple[str, ...] = ()
    budget_exhausted: bool = False
    bound_admissible: bool | None = None
    optimal: bool | None = None
    oracle_value: float | None = None

    def as_measurement(self) -> dict[str, object]:
        return {
            "world": self.world,
            "strategy": self.strategy,
            "expanded": self.expanded,
            "generated": self.generated,
            "rejected_count": len(self.rejected),
            "rejected": self.rejected[:4],
            "pruned_count": len(self.pruned),
            "best_value": self.best_value,
            "best_path": list(self.best_path),
            "budget_exhausted": self.budget_exhausted,
            "bound_admissible": self.bound_admissible,
            "oracle_value": self.oracle_value,
            "optimal": self.optimal,
            "modality": {
                "observed_states": 1,
                "simulated_states": self.generated,
                "claim": "simulated values are never reported as observed",
            },
        }


def _children(world: BranchWorld, state: Hashable, assumptions: frozenset[str]):
    for name, child, cost, new_assumptions in world.children(state):
        yield name, child, cost, assumptions | new_assumptions


def explore_branches(
    world: BranchWorld, config: KetamineConfig | None = None
) -> BranchReport:
    """Expand the possible-world tree under the configured strategy."""
    config = config or KetamineConfig()
    admissibility = world.bound_is_admissible()
    oracle = world.best_leaf()
    strategy = (
        "diversity_first"
        if config.diversity_first
        else ("beam" if config.beam_width else "bound_guided_best_first")
    )
    report = BranchReport(
        world=world.name,
        strategy=strategy,
        bound_admissible=bool(admissibility["admissible"]),
        oracle_value=float(oracle["value"]) if oracle.get("found") else None,
    )
    incumbent: float = float("-inf")
    best_path: tuple[str, ...] = ()

    # The frontier holds only consistent, simulated branches.
    frontier: list[tuple[Hashable, tuple[str, ...], float, frozenset[str]]] = [
        (world.root, (), 0.0, frozenset())
    ]
    report.generated = 1
    layer = 0
    while frontier:
        if report.expanded >= config.node_budget:
            report.budget_exhausted = True
            break
        if config.beam_width or config.diversity_first:
            batch, frontier = frontier, []
        else:
            batch = [max(frontier, key=lambda item: (world.bound(item[0]), repr(item[0])))]
            frontier = [item for item in frontier if item is not batch[0]]
        children: list[tuple[Hashable, tuple[str, ...], float, frozenset[str]]] = []
        for state, path, cost, assumptions in batch:
            if report.expanded >= config.node_budget:
                report.budget_exhausted = True
                break
            report.expanded += 1
            if world.is_terminal(state):
                value = world.value(state)
                if value > incumbent:
                    incumbent, best_path = value, path
                continue
            # Prune only when a *verified* admissible bound says it is safe.
            if admissibility["admissible"] and world.bound(state) <= incumbent + 1e-12:
                report.pruned.append(
                    {"state": str(state), "bound": world.bound(state), "incumbent": incumbent}
                )
                continue
            for name, child, step, new_assumptions in _children(world, state, assumptions):
                consistent, reason = world.consistent(new_assumptions)
                report.generated += 1
                if not consistent:
                    report.rejected.append(
                        {
                            "branch": name,
                            "state": str(child),
                            "assumptions": sorted(new_assumptions),
                            "reason": reason,
                            "status": REJECTED,
                        }
                    )
                    continue
                children.append((child, path + (name,), cost + step, new_assumptions))
        if config.beam_width or config.diversity_first:
            layer += 1
            if config.diversity_first:
                children = _diverse_order(children, world)
            else:
                children.sort(key=lambda item: (-world.bound(item[0]), repr(item[0])))
            width = config.beam_width or len(children)
            frontier = children[:width]
        else:
            frontier.extend(children)
    report.best_value = None if incumbent == float("-inf") else incumbent
    report.best_path = best_path
    if report.oracle_value is not None and report.best_value is not None:
        report.optimal = abs(report.best_value - report.oracle_value) <= 1e-9
    return report


def _diverse_order(
    children: Sequence[tuple[Hashable, tuple[str, ...], float, frozenset[str]]],
    world: BranchWorld,
) -> list[tuple[Hashable, tuple[str, ...], float, frozenset[str]]]:
    """Order by declared novelty first, then greedy max-min dissimilarity.

    Diversity is a hedge against correlated error, not evidence of value.  When
    the world declares a novelty function it is used directly, so
    ``novelty_trap_world`` tests novelty-driven exploration rather than a string
    similarity proxy.
    """
    if world.novelty is not None:
        return sorted(children, key=lambda item: (-world.novelty(item[0]), repr(item[0])))
    remaining = list(children)
    chosen: list[tuple[Hashable, tuple[str, ...], float, frozenset[str]]] = []
    while remaining:
        if not chosen:
            pick = min(remaining, key=lambda item: repr(item[0]))
        else:
            pick = max(
                remaining,
                key=lambda item: (
                    min(_distance(repr(item[0]), repr(other[0])) for other in chosen),
                    repr(item[0]),
                ),
            )
        chosen.append(pick)
        remaining.remove(pick)
    return chosen


def _distance(left: str, right: str) -> int:
    """Symmetric-difference size on character multisets: cheap and deterministic."""
    return len(set(left) ^ set(right)) + abs(len(left) - len(right))


class Ketamine:
    """The branching operator over the shared substrate."""

    name = "KETAMINE"

    def __init__(self, world: BranchWorld, config: KetamineConfig | None = None) -> None:
        self.world = world
        self.config = config or KetamineConfig()
        self.report: BranchReport | None = None
        self.certificates: list[dict[str, object]] = []

    def observe(self, state: State) -> State:
        representation = dict(state.representation)
        representation.setdefault("root", self.world.root)
        representation["evidence"] = sorted(self.world.evidence)
        return state.with_representation(representation)

    def propose(self, state: State) -> list[Candidate]:
        """One candidate per admissible first intervention, plus the rejected ones.

        Rejected branches are proposed *as rejected* rather than hidden, so the
        certificate shows what was refused and why.
        """
        out: list[Candidate] = []
        for name, child, cost, assumptions in self.world.children(self.world.root):
            consistent, reason = self.world.consistent(assumptions)
            out.append(
                Candidate(
                    name=name,
                    operator=self.name,
                    declared=Declaration(
                        cost=cost,
                        evidence=tuple(sorted(self.world.evidence)),
                        uncertainty=None,
                        information_gain=None,
                        residue={
                            "status": SIMULATED if consistent else REJECTED,
                            "assumptions": sorted(assumptions),
                            "inconsistency": reason,
                            "bound": self.world.bound(child),
                        },
                        invariants=("simulated states are never reported as observed",),
                    ),
                    payload={"state": child, "consistent": consistent},
                )
            )
        return out

    def select(self, state: State, candidates: Sequence[Candidate]) -> Candidate | None:
        self.report = explore_branches(self.world, self.config)
        consistent = [item for item in candidates if item.payload["consistent"]]
        certificate: dict[str, object] = {
            "search": self.report.as_measurement(),
            "rejected_first_moves": [
                {"branch": item.name, "why": item.declared.residue["inconsistency"]}
                for item in candidates
                if not item.payload["consistent"]
            ],
        }
        if not consistent:
            certificate["decision"] = "ABSTAIN: every first intervention contradicts the evidence"
            self.certificates.append(certificate)
            return None
        if self.report.best_path:
            first = self.report.best_path[0]
            chosen = next((item for item in consistent if item.name == first), consistent[0])
            certificate["decision"] = f"SELECT {chosen.name}"
            certificate["reason"] = (
                "first move of the best consistent simulated path"
                + (
                    "; pruning was safe under a verified admissible bound"
                    if self.report.bound_admissible
                    else "; no admissible bound, so optimality is not claimed"
                )
            )
        else:
            chosen = consistent[0]
            certificate["decision"] = f"SELECT {chosen.name}"
            certificate["reason"] = "no terminal reached within budget; taking a consistent branch"
        self.certificates.append(certificate)
        return chosen

    def apply(self, state: State, candidate: Candidate) -> State:
        representation = dict(state.representation)
        representation["chosen_branch"] = candidate.name
        representation["branch_state"] = candidate.payload["state"]
        representation["status"] = SIMULATED
        return state.with_representation(representation).charge(1)

    def validate(self, state: State, candidate: Candidate, after: State) -> bool | None:
        """A selected branch must be consistent and must still be simulated."""
        return bool(candidate.payload["consistent"]) and after.representation["status"] == SIMULATED

    def conclude(self, state: State, turn_index: int, validated: bool | None) -> tuple[Decision, str]:
        assert self.report is not None
        if validated is False:
            return Decision.ABSTAIN, "selected branch failed the consistency check"
        if self.report.optimal is True:
            return Decision.STOP, "best consistent branch found and proved optimal by an admissible bound"
        if self.report.budget_exhausted:
            return Decision.STOP, "node budget exhausted; best branch found so far is not proved optimal"
        return Decision.STOP, "search space exhausted without an optimality certificate"
